service:
  name: quarkus-app
  image: quay.io/dborrego/workshop-tekton-argocd-app-quarkus
  version: 0.1

deployment:
  replicas: 2
  port: 8080
  health:
    liveness: /q/health/live
    readiness: /q/health/live
  resources: 
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

config:
  env:
